import 'controller/subscription_two_controller.dart';import 'package:flutter/material.dart';import 'package:patientmodule/core/app_export.dart';import 'package:patientmodule/widgets/custom_button.dart';
// ignore_for_file: must_be_immutable
class SubscriptionTwoDialog extends StatelessWidget {SubscriptionTwoDialog(this.controller);

SubscriptionTwoController controller;

@override Widget build(BuildContext context) { return Container(child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.center, mainAxisAlignment: MainAxisAlignment.center, children: [Container(width: double.infinity, margin: getMargin(left: 12, top: 206, right: 12, bottom: 230), decoration: AppDecoration.fillWhiteA700.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.center, mainAxisAlignment: MainAxisAlignment.start, children: [Container(width: getHorizontalSize(259.00), margin: getMargin(left: 16, top: 16, right: 16), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_are_you_sure_wa2".tr, style: TextStyle(color: ColorConstant.black900, fontSize: getFontSize(20), fontFamily: 'SemplicitaPro', fontWeight: FontWeight.w700, height: 1.00)), TextSpan(text: "lbl2".tr, style: TextStyle(color: ColorConstant.black900, fontSize: getFontSize(20), fontFamily: 'Roboto', fontWeight: FontWeight.w700, height: 1.00))]), textAlign: TextAlign.center)), Container(width: getHorizontalSize(255.00), margin: getMargin(left: 16, top: 12, right: 16), child: Text("msg_you_will_lose_a".tr, maxLines: null, textAlign: TextAlign.center, style: AppStyle.txtSemplicitaProRegular16Gray603.copyWith(height: 1.25))), Padding(padding: getPadding(left: 16, top: 15, right: 16, bottom: 16), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.center, mainAxisSize: MainAxisSize.max, children: [CustomButton(width: 144, text: "lbl_keep_plan".tr, variant: ButtonVariant.OutlineGray500, fontStyle: ButtonFontStyle.SemplicitaProRegular14, onTap: onTapBtnKeepplan), CustomButton(width: 144, text: "lbl_cancel".tr.toUpperCase(), fontStyle: ButtonFontStyle.SemplicitaProMedium14WhiteA700, onTap: onTapBtnCancel)]))]))])); } 
onTapBtnKeepplan() { Get.toNamed(AppRoutes.subscriptionFourScreen); } 
onTapBtnCancel() { Get.back(); } 
 }
